/*
 * Revenium Metering API
 * Revenium Metering API
 *
 * OpenAPI spec version: 1.14.0-SNAPSHOT
 * Contact: info@revenium.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ElementDTO model module.
 * @module model/ElementDTO
 * @version 1.14.0-SNAPSHOT
 */
export default class ElementDTO {
  /**
   * Constructs a new <code>ElementDTO</code>.
   * Dynamic metering elements
   * @alias module:model/ElementDTO
   * @class
   * @param name {String} 
   * @param value {String} 
   */
  constructor(name, value) {
    this.name = name;
    this.value = value;
  }

  /**
   * Constructs a <code>ElementDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ElementDTO} obj Optional instance to populate.
   * @return {module:model/ElementDTO} The populated <code>ElementDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ElementDTO();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
ElementDTO.prototype.name = undefined;

/**
 * @member {String} value
 */
ElementDTO.prototype.value = undefined;

