/*
 * Revenium Metering API
 * Revenium Metering API
 *
 * OpenAPI spec version: 1.14.0-SNAPSHOT
 * Contact: info@revenium.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import ApiEventDTO from './model/ApiEventDTO';
import ElementDTO from './model/ElementDTO';
import MeteringRequestDTO from './model/MeteringRequestDTO';
import Unit from './model/Unit';
import EventsApi from './api/EventsApi';
import MetringApi from './api/MetringApi';

/**
* Revenium_Metering_API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ReveniumMeteringApi = require('index'); // See note below*.
* var xxxSvc = new ReveniumMeteringApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ReveniumMeteringApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ReveniumMeteringApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ReveniumMeteringApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.14.0-SNAPSHOT
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ApiEventDTO model constructor.
     * @property {module:model/ApiEventDTO}
     */
    ApiEventDTO,

    /**
     * The ElementDTO model constructor.
     * @property {module:model/ElementDTO}
     */
    ElementDTO,

    /**
     * The MeteringRequestDTO model constructor.
     * @property {module:model/MeteringRequestDTO}
     */
    MeteringRequestDTO,

    /**
     * The Unit model constructor.
     * @property {module:model/Unit}
     */
    Unit,

    /**
    * The EventsApi service constructor.
    * @property {module:api/EventsApi}
    */
    EventsApi,

    /**
    * The MetringApi service constructor.
    * @property {module:api/MetringApi}
    */
    MetringApi
};
