/*
 * Revenium Metering API
 * Revenium Metering API
 *
 * OpenAPI spec version: 1.14.0-SNAPSHOT
 * Contact: info@revenium.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ReveniumMeteringApi);
  }
}(this, function(expect, ReveniumMeteringApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ReveniumMeteringApi.EventsApi();
  });

  describe('(package)', function() {
    describe('EventsApi', function() {
      describe('saveEvent', function() {
        it('should call saveEvent successfully', function(done) {
          // TODO: uncomment, update parameter values for saveEvent call
          /*

          instance.saveEvent(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
